//! A window: one PTY-attached child process and its libghostty terminal
//! state. All child output is parsed through ghostty-vt so the full screen
//! (including scrollback, styles, modes, and cursor) can be rehydrated at
//! any time for attach, window switching, and hardcopy.

const std = @import("std");
const posix = std.posix;
const vt = @import("ghostty-vt");
const altscreen = @import("altscreen.zig");
const ptypkg = @import("pty.zig");
const protocol = @import("protocol.zig");

const log = std.log.scoped(.window);

pub const Window = struct {
    alloc: std.mem.Allocator,

    /// PTY master; -1 once the child is gone.
    pty_fd: posix.fd_t,
    child_pid: posix.pid_t,
    dead: bool = false,

    /// Fallback title: the command that was launched.
    command_title: []const u8,

    /// Wall-clock time (milliseconds) of the most recent child output,
    /// maintained by the daemon. Drives `wait --idle`.
    last_output_ms: i64,

    /// True while this window is the active window of an attached client.
    /// Controls whether query responses (DSR, DA, ...) are answered by
    /// the daemon or left to the client's real terminal.
    passthrough: bool = false,

    /// True while feeding bytes whose passthrough copy was discarded
    /// (see `feedDiscarded`); forces daemon-side query responses even
    /// when passing through.
    feeding_discarded: bool = false,

    /// Strips alternate-screen toggles from passthrough output; the
    /// daemon repaints from terminal state on screen switches instead.
    alt_filter: altscreen.Filter = .{ .discard_after_switch = true },

    term: vt.Terminal,
    stream: Stream,

    pub const Stream = vt.TerminalStream;

    /// Window is heap-allocated and pinned: the stream handler keeps a
    /// pointer to `term` and effects callbacks recover the Window with
    /// @fieldParentPtr.
    pub fn create(
        alloc: std.mem.Allocator,
        argv: []const []const u8,
        env: *std.process.EnvMap,
        rows: u16,
        cols: u16,
    ) !*Window {
        const self = try alloc.create(Window);
        errdefer alloc.destroy(self);

        const spawned = try ptypkg.spawnInPty(alloc, .{
            .argv = argv,
            .env = env,
            .size = ptypkg.makeWinsize(rows, cols),
        });
        errdefer posix.close(spawned.master);

        self.* = .{
            .alloc = alloc,
            .pty_fd = spawned.master,
            .child_pid = spawned.pid,
            .command_title = try alloc.dupe(u8, argv[0]),
            .last_output_ms = std.time.milliTimestamp(),
            .term = undefined,
            .stream = undefined,
        };
        errdefer alloc.free(self.command_title);

        self.term = try vt.Terminal.init(alloc, .{
            .cols = cols,
            .rows = rows,
            .max_scrollback = 512 * 1024,
        });
        errdefer self.term.deinit(alloc);

        var handler: Stream.Handler = .init(&self.term);
        handler.effects = .{
            .write_pty = effectWritePty,
            .bell = null,
            .color_scheme = null,
            .device_attributes = effectDeviceAttributes,
            .enquiry = null,
            .size = effectSize,
            .title_changed = null,
            .pwd_changed = null,
            .xtversion = effectXtversion,
        };
        self.stream = .initAlloc(alloc, handler);

        return self;
    }

    pub fn destroy(self: *Window) void {
        self.stream.deinit();
        self.term.deinit(self.alloc);
        self.alloc.free(self.command_title);
        if (self.pty_fd >= 0) posix.close(self.pty_fd);
        self.alloc.destroy(self);
    }

    fn fromHandler(handler: *Stream.Handler) *Window {
        const stream: *Stream = @alignCast(@fieldParentPtr("handler", handler));
        return @alignCast(@fieldParentPtr("stream", stream));
    }

    /// Query responses generated by the terminal (DSR, DECRQM, OSC color
    /// queries, ...). When a client is attached and this window is being
    /// passed through raw, the client's real terminal sees the query and
    /// answers it, so the daemon stays quiet to avoid double responses.
    /// Bytes the passthrough discarded never reach that terminal, so
    /// queries among them are answered here after all.
    fn effectWritePty(handler: *Stream.Handler, data: [:0]const u8) void {
        const self = fromHandler(handler);
        if (self.passthrough and !self.feeding_discarded) return;
        if (self.pty_fd < 0) return;
        protocol.writeAll(self.pty_fd, data) catch |err| {
            log.warn("window: failed writing query response: {}", .{err});
        };
    }

    // The device attributes response type is not re-exported by the
    // ghostty-vt root, so derive it from the effects callback signature.
    const DeviceAttributes = EffectReturn("device_attributes");

    fn EffectReturn(comptime field_name: []const u8) type {
        const Effects = Stream.Handler.Effects;
        const field = std.meta.fieldInfo(
            Effects,
            @field(std.meta.FieldEnum(Effects), field_name),
        );
        const Fn = @typeInfo(field.type).optional.child;
        return @typeInfo(@typeInfo(Fn).pointer.child).@"fn".return_type.?;
    }

    fn effectDeviceAttributes(handler: *Stream.Handler) DeviceAttributes {
        _ = handler;
        return .{};
    }

    fn effectSize(handler: *Stream.Handler) ?vt.size_report.Size {
        const self = fromHandler(handler);
        return .{
            .rows = self.term.rows,
            .columns = self.term.cols,
            .cell_width = 8,
            .cell_height = 16,
        };
    }

    fn effectXtversion(handler: *Stream.Handler) []const u8 {
        _ = handler;
        return "boo " ++ @import("main.zig").version;
    }

    /// Feed child output into the terminal emulator.
    pub fn feed(self: *Window, bytes: []const u8) void {
        self.stream.nextSlice(bytes);
    }

    /// Feed child output that was dropped from the passthrough stream
    /// (everything after an alternate-screen switch until the repaint).
    /// The client's real terminal never sees these bytes, so queries in
    /// them must be answered by the daemon or the application blocks
    /// waiting for a response that nobody sends.
    pub fn feedDiscarded(self: *Window, bytes: []const u8) void {
        self.feeding_discarded = true;
        defer self.feeding_discarded = false;
        self.stream.nextSlice(bytes);
    }

    pub fn writeInput(self: *Window, bytes: []const u8) !void {
        if (self.pty_fd < 0) return error.WindowDead;
        try protocol.writeAll(self.pty_fd, bytes);
    }

    pub fn resize(self: *Window, rows: u16, cols: u16) !void {
        try self.term.resize(self.alloc, cols, rows);
        if (self.pty_fd >= 0) {
            try ptypkg.Pty.setSize(self.pty_fd, ptypkg.makeWinsize(rows, cols));
        }
    }

    pub fn title(self: *Window) []const u8 {
        if (self.term.getTitle()) |t| {
            if (t.len > 0) return t;
        }
        return self.command_title;
    }

    /// Whether the active screen has any kitty keyboard protocol
    /// flags enabled. While attached, the user's terminal mirrors
    /// this state, so the C-a prefix arrives CSI-u encoded.
    pub fn kittyKeysActive(self: *Window) bool {
        return self.term.screens.active.kitty_keyboard.current().int() != 0;
    }

    /// Whether the application is on the alternate screen. The
    /// passthrough strips screen toggles, so clients cannot tell
    /// from the byte stream.
    pub fn onAltScreen(self: *Window) bool {
        return self.term.screens.active_key == .alternate;
    }

    /// Plain-text dump of the screen, for peek.
    pub fn plainScreen(self: *Window, alloc: std.mem.Allocator) ![]const u8 {
        return self.term.plainString(alloc);
    }

    /// Plain-text dump including the full scrollback history.
    pub fn plainScrollback(self: *Window, alloc: std.mem.Allocator) ![]const u8 {
        return self.term.screens.active.dumpStringAlloc(alloc, .{ .screen = .{} });
    }

    /// VT bytes that reproduce this window's visible screen on a
    /// freshly sanitized terminal: contents, styles, cursor, and modes.
    pub fn repaint(self: *Window, alloc: std.mem.Allocator) ![]u8 {
        var raw: std.Io.Writer.Allocating = .init(alloc);
        defer raw.deinit();

        var formatter: vt.formatter.TerminalFormatter = .init(&self.term, .{ .emit = .vt });
        // Repaint the visible screen only. Every canvas drops
        // scrolled-off rows (attached clients render in the user
        // terminal's alternate screen and ui views keep no
        // scrollback), and the formatter always trims trailing blank
        // rows from its dump. Including history scrolls the canvas,
        // so whenever the screen ends in blank rows the content lands
        // shifted up by the trimmed count and the cursor restore below
        // points at the wrong row; every relative redraw the
        // application makes after that corrupts the client's view.
        formatter.content = .{ .selection = self.screenSelection() };
        formatter.extra = .{
            // Keep the client's own palette: colors are emitted as
            // palette references, not redefined.
            .palette = false,
            .modes = true,
            .scrolling_region = true,
            .tabstops = true,
            .pwd = false,
            .keyboard = true,
            .screen = .all,
        };
        try raw.writer.print("{f}", .{formatter});

        // The formatter re-emits alternate-screen modes when the window
        // is on the alt screen, but the client canvas always shows the
        // active screen, so screen toggles must never reach it.
        var out: std.Io.Writer.Allocating = .init(alloc);
        defer out.deinit();
        try out.writer.writeAll(sanitize_sequence);
        // The formatter does not emit the title, so without this the
        // client terminal's title would go stale across reattach and
        // window switches.
        try writeTitle(self.title(), &out.writer);
        var filter: altscreen.Filter = .{};
        _ = try filter.feed(raw.writer.buffered(), &out.writer);

        // Tabstop and scrolling-region rehydration is emitted after the
        // screen extras and moves the cursor, so position it last.
        try self.writeCursorPos(&out.writer);

        return alloc.dupe(u8, out.writer.buffered());
    }

    /// Selection spanning the visible screen of the active terminal
    /// screen, so a repaint excludes scrollback history. Null (the
    /// formatter's dump-everything default) only if the pins cannot
    /// resolve, which a sized terminal never produces.
    fn screenSelection(self: *Window) ?vt.Selection {
        const pages = &self.term.screens.active.pages;
        const tl = pages.pin(.{ .active = .{ .x = 0, .y = 0 } }) orelse return null;
        const br = pages.pin(.{ .active = .{
            .x = self.term.cols - 1,
            .y = self.term.rows - 1,
        } }) orelse return null;
        return vt.Selection.init(tl, br, false);
    }

    fn writeCursorPos(self: *Window, writer: *std.Io.Writer) !void {
        const cursor = &self.term.screens.active.cursor;
        var row: usize = cursor.y;
        var col: usize = cursor.x;
        // CUP is relative to the scrolling region in origin mode.
        if (self.term.modes.get(.origin)) {
            row -|= self.term.scrolling_region.top;
            col -|= self.term.scrolling_region.left;
        }
        try writer.print("\x1b[{d};{d}H", .{ row + 1, col + 1 });
    }
};

/// OSC 2: set the client terminal's window title. Control bytes are
/// dropped so the title text cannot terminate or corrupt the sequence.
fn writeTitle(title: []const u8, writer: *std.Io.Writer) !void {
    try writer.writeAll("\x1b]2;");
    for (title) |byte| {
        if (byte < 0x20 or byte == 0x7f) continue;
        try writer.writeByte(byte);
    }
    try writer.writeByte(0x07);
}

/// Resets every piece of terminal state a window's repaint or
/// passthrough may have changed, without touching the screen choice or
/// the saved cursor. DECSTR is deliberately avoided: it clears the
/// cursor position that `1049h` saved, which the client needs intact
/// for the final `1049l` restore on detach.
pub const reset_state_sequence =
    "\x0f\x1b(B" ++ // locking shift and G0 charset to ASCII
    "\x1b[0m" ++ // SGR reset
    "\x1b[0 q" ++ // default cursor style
    "\x1b[?1l\x1b[?5l\x1b[?6l\x1b[?7h" ++ // cursor keys, reverse video, origin, autowrap
    "\x1b[4l" ++ // insert mode off
    "\x1b[r\x1b[?69l" ++ // scrolling margins reset
    "\x1b[?25h" ++ // cursor visible
    "\x1b[?1000l\x1b[?1002l\x1b[?1003l\x1b[?1005l\x1b[?1006l" ++ // mouse off
    "\x1b[?2004l" ++ // bracketed paste off
    "\x1b[?1004l" ++ // focus reporting off
    "\x1b[>4;0m" ++ // modifyOtherKeys off
    "\x1b[=0;1u"; // kitty keyboard flags cleared

/// Repaint preamble: reset state, then clear the client canvas. The
/// canvas is the client terminal's own alternate screen, so no screen
/// toggles belong here.
pub const sanitize_sequence = reset_state_sequence ++ "\x1b[H\x1b[2J";

test "window state machine without a child" {
    // Exercise the terminal+stream wiring directly (no PTY): construct
    // the pieces the same way Window.create does.
    const alloc = std.testing.allocator;

    var term = try vt.Terminal.init(alloc, .{ .cols = 20, .rows = 5 });
    defer term.deinit(alloc);
    var stream = term.vtStream();
    defer stream.deinit();

    stream.nextSlice("hello \x1b[1;31mred\x1b[0m\r\nline2");

    const plain = try term.plainString(alloc);
    defer alloc.free(plain);
    try std.testing.expect(std.mem.indexOf(u8, plain, "hello red") != null);
    try std.testing.expect(std.mem.indexOf(u8, plain, "line2") != null);

    // Styled repaint contains the bold+red SGR introducer and content.
    var out: std.Io.Writer.Allocating = .init(alloc);
    defer out.deinit();
    var formatter: vt.formatter.TerminalFormatter = .init(&term, .{ .emit = .vt });
    formatter.extra = .{
        .palette = false,
        .modes = true,
        .scrolling_region = true,
        .tabstops = false,
        .pwd = false,
        .keyboard = true,
        .screen = .all,
    };
    try out.writer.print("{f}", .{formatter});
    const repainted = out.writer.buffered();
    try std.testing.expect(std.mem.indexOf(u8, repainted, "red") != null);
    try std.testing.expect(std.mem.indexOf(u8, repainted, "\x1b[") != null);
}

test "repaint reproduces the screen once output has scrolled" {
    // The shape every frame-based TUI leaves behind (Claude Code's
    // idle prompt is the motivating case): output has scrolled into
    // history, the application then redraws a short frame at the top
    // and erases the rest, leaving trailing blank rows below the
    // cursor. The repaint must land every row and the cursor exactly
    // where the emulator has them, or every subsequent relative
    // redraw by the application corrupts the client's view.
    const alloc = std.testing.allocator;

    var win: Window = .{
        .alloc = alloc,
        .pty_fd = -1,
        .child_pid = -1,
        .command_title = "test",
        .last_output_ms = 0,
        .term = try vt.Terminal.init(alloc, .{
            .cols = 20,
            .rows = 5,
            .max_scrollback = 512 * 1024,
        }),
        .stream = undefined,
    };
    defer win.term.deinit(alloc);
    var stream = win.term.vtStream();
    defer stream.deinit();

    // Eight lines scroll three into history, then a two-row frame
    // is drawn and everything below it erased: the screen is
    // L4, "boo>", and three blank rows, cursor after the "boo>".
    stream.nextSlice("L1\r\nL2\r\nL3\r\nL4\r\nL5\r\nL6\r\nL7\r\nL8");
    stream.nextSlice("\x1b[2;1Hboo>\x1b[0J");

    const bytes = try win.repaint(alloc);
    defer alloc.free(bytes);

    // Replay on a fresh terminal of the same size, standing in for
    // an attached client's alternate-screen canvas or a ui view.
    var canvas = try vt.Terminal.init(alloc, .{ .cols = 20, .rows = 5 });
    defer canvas.deinit(alloc);
    var canvas_stream = canvas.vtStream();
    defer canvas_stream.deinit();
    canvas_stream.nextSlice(bytes);

    const want = try win.term.plainString(alloc);
    defer alloc.free(want);
    const got = try canvas.plainString(alloc);
    defer alloc.free(got);
    try std.testing.expectEqualStrings(want, got);

    const want_cursor = win.term.screens.active.cursor;
    const got_cursor = canvas.screens.active.cursor;
    try std.testing.expectEqual(want_cursor.y, got_cursor.y);
    try std.testing.expectEqual(want_cursor.x, got_cursor.x);
}

test "title set via OSC is tracked and emitted sanitized" {
    const alloc = std.testing.allocator;

    var term = try vt.Terminal.init(alloc, .{ .cols = 20, .rows = 5 });
    defer term.deinit(alloc);
    var stream = term.vtStream();
    defer stream.deinit();

    stream.nextSlice("\x1b]2;my title\x07");
    try std.testing.expectEqualStrings("my title", term.getTitle().?);

    var buf: [64]u8 = undefined;
    var writer = std.Io.Writer.fixed(&buf);
    try writeTitle(term.getTitle().?, &writer);
    try std.testing.expectEqualStrings("\x1b]2;my title\x07", writer.buffered());

    // Control bytes in a title cannot break out of the sequence.
    writer = std.Io.Writer.fixed(&buf);
    try writeTitle("a\x1b\x07b\x7f!", &writer);
    try std.testing.expectEqualStrings("\x1b]2;ab!\x07", writer.buffered());
}
