//! A window: one PTY-attached child process and its libghostty terminal
//! state. All child output is parsed through ghostty-vt so the full screen
//! (including scrollback, styles, modes, and cursor) can be rehydrated at
//! any time for attach, window switching, and hardcopy.

const std = @import("std");
const posix = std.posix;
const vt = @import("ghostty-vt");
const ptypkg = @import("pty.zig");
const protocol = @import("protocol.zig");

const log = std.log.scoped(.window);

pub const Window = struct {
    alloc: std.mem.Allocator,
    id: u16,

    /// PTY master; -1 once the child is gone.
    pty_fd: posix.fd_t,
    child_pid: posix.pid_t,
    dead: bool = false,

    /// Fallback title: the command that was launched.
    command_title: []const u8,

    /// True while this window is the active window of an attached client.
    /// Controls whether query responses (DSR, DA, ...) are answered by
    /// the daemon or left to the client's real terminal.
    passthrough: bool = false,

    term: vt.Terminal,
    stream: Stream,

    pub const Stream = vt.TerminalStream;

    /// Window is heap-allocated and pinned: the stream handler keeps a
    /// pointer to `term` and effects callbacks recover the Window with
    /// @fieldParentPtr.
    pub fn create(
        alloc: std.mem.Allocator,
        id: u16,
        argv: []const []const u8,
        env: *std.process.EnvMap,
        rows: u16,
        cols: u16,
    ) !*Window {
        const self = try alloc.create(Window);
        errdefer alloc.destroy(self);

        const spawned = try ptypkg.spawnInPty(alloc, .{
            .argv = argv,
            .env = env,
            .size = ptypkg.makeWinsize(rows, cols),
        });
        errdefer posix.close(spawned.master);

        self.* = .{
            .alloc = alloc,
            .id = id,
            .pty_fd = spawned.master,
            .child_pid = spawned.pid,
            .command_title = try alloc.dupe(u8, argv[0]),
            .term = undefined,
            .stream = undefined,
        };
        errdefer alloc.free(self.command_title);

        self.term = try vt.Terminal.init(alloc, .{
            .cols = cols,
            .rows = rows,
            .max_scrollback = 512 * 1024,
        });
        errdefer self.term.deinit(alloc);

        var handler: Stream.Handler = .init(&self.term);
        handler.effects = .{
            .write_pty = effectWritePty,
            .bell = null,
            .color_scheme = null,
            .device_attributes = effectDeviceAttributes,
            .enquiry = null,
            .size = effectSize,
            .title_changed = null,
            .pwd_changed = null,
            .xtversion = effectXtversion,
        };
        self.stream = .initAlloc(alloc, handler);

        return self;
    }

    pub fn destroy(self: *Window) void {
        self.stream.deinit();
        self.term.deinit(self.alloc);
        self.alloc.free(self.command_title);
        if (self.pty_fd >= 0) posix.close(self.pty_fd);
        self.alloc.destroy(self);
    }

    fn fromHandler(handler: *Stream.Handler) *Window {
        const stream: *Stream = @alignCast(@fieldParentPtr("handler", handler));
        return @alignCast(@fieldParentPtr("stream", stream));
    }

    /// Query responses generated by the terminal (DSR, DECRQM, OSC color
    /// queries, ...). When a client is attached and this window is being
    /// passed through raw, the client's real terminal sees the query and
    /// answers it, so the daemon stays quiet to avoid double responses.
    fn effectWritePty(handler: *Stream.Handler, data: [:0]const u8) void {
        const self = fromHandler(handler);
        if (self.passthrough) return;
        if (self.pty_fd < 0) return;
        protocol.writeAll(self.pty_fd, data) catch |err| {
            log.warn("window {d}: failed writing query response: {}", .{ self.id, err });
        };
    }

    // The device attributes response type is not re-exported by the
    // ghostty-vt root, so derive it from the effects callback signature.
    const DeviceAttributes = EffectReturn("device_attributes");

    fn EffectReturn(comptime field_name: []const u8) type {
        const Effects = Stream.Handler.Effects;
        const field = std.meta.fieldInfo(
            Effects,
            @field(std.meta.FieldEnum(Effects), field_name),
        );
        const Fn = @typeInfo(field.type).optional.child;
        return @typeInfo(@typeInfo(Fn).pointer.child).@"fn".return_type.?;
    }

    fn effectDeviceAttributes(handler: *Stream.Handler) DeviceAttributes {
        _ = handler;
        return .{};
    }

    fn effectSize(handler: *Stream.Handler) ?vt.size_report.Size {
        const self = fromHandler(handler);
        return .{
            .rows = self.term.rows,
            .columns = self.term.cols,
            .cell_width = 8,
            .cell_height = 16,
        };
    }

    fn effectXtversion(handler: *Stream.Handler) []const u8 {
        _ = handler;
        return "ghostscreen " ++ @import("main.zig").version;
    }

    /// Feed child output into the terminal emulator.
    pub fn feed(self: *Window, bytes: []const u8) void {
        self.stream.nextSlice(bytes);
    }

    pub fn writeInput(self: *Window, bytes: []const u8) !void {
        if (self.pty_fd < 0) return error.WindowDead;
        try protocol.writeAll(self.pty_fd, bytes);
    }

    pub fn resize(self: *Window, rows: u16, cols: u16) !void {
        try self.term.resize(self.alloc, cols, rows);
        if (self.pty_fd >= 0) {
            try ptypkg.Pty.setSize(self.pty_fd, ptypkg.makeWinsize(rows, cols));
        }
    }

    pub fn title(self: *Window) []const u8 {
        if (self.term.getTitle()) |t| {
            if (t.len > 0) return t;
        }
        return self.command_title;
    }

    /// Plain-text dump of the screen, for hardcopy.
    pub fn plainScreen(self: *Window, alloc: std.mem.Allocator) ![]const u8 {
        return self.term.plainString(alloc);
    }

    /// VT bytes that reproduce this window's full terminal state on a
    /// freshly sanitized terminal: contents, styles, cursor, and modes.
    pub fn repaint(self: *Window, alloc: std.mem.Allocator) ![]u8 {
        var out: std.Io.Writer.Allocating = .init(alloc);
        defer out.deinit();

        try out.writer.writeAll(sanitize_sequence);

        var formatter: vt.formatter.TerminalFormatter = .init(&self.term, .{ .emit = .vt });
        formatter.extra = .{
            // Keep the client's own palette: colors are emitted as
            // palette references, not redefined.
            .palette = false,
            .modes = true,
            .scrolling_region = true,
            .tabstops = true,
            .pwd = false,
            .keyboard = true,
            .screen = .all,
        };
        try out.writer.print("{f}", .{formatter});

        // Tabstop and scrolling-region rehydration is emitted after the
        // screen extras and moves the cursor, so position it last.
        try self.writeCursorPos(&out.writer);

        return alloc.dupe(u8, out.writer.buffered());
    }

    fn writeCursorPos(self: *Window, writer: *std.Io.Writer) !void {
        const cursor = &self.term.screens.active.cursor;
        var row: usize = cursor.y;
        var col: usize = cursor.x;
        // CUP is relative to the scrolling region in origin mode.
        if (self.term.modes.get(.origin)) {
            row -|= self.term.scrolling_region.top;
            col -|= self.term.scrolling_region.left;
        }
        try writer.print("\x1b[{d};{d}H", .{ row + 1, col + 1 });
    }
};

/// Reset a real terminal to a known state before replaying a window:
/// leave alternate screens, soft reset, drop reporting modes the
/// previous window may have enabled, then clear.
pub const sanitize_sequence = "\x1b[?1049l\x1b[?1047l\x1b[?47l" ++ // exit alt screens
    "\x1b[!p" ++ // DECSTR soft reset
    "\x1b[?1000l\x1b[?1002l\x1b[?1003l\x1b[?1005l\x1b[?1006l" ++ // mouse off
    "\x1b[?2004l" ++ // bracketed paste off
    "\x1b[?1004l" ++ // focus reporting off
    "\x1b[>4;0m" ++ // modifyOtherKeys off
    "\x1b[=0;1u" ++ // kitty keyboard flags cleared
    "\x1b[0m\x1b[H\x1b[2J"; // SGR reset, home, clear

test "window state machine without a child" {
    // Exercise the terminal+stream wiring directly (no PTY): construct
    // the pieces the same way Window.create does.
    const alloc = std.testing.allocator;

    var term = try vt.Terminal.init(alloc, .{ .cols = 20, .rows = 5 });
    defer term.deinit(alloc);
    var stream = term.vtStream();
    defer stream.deinit();

    stream.nextSlice("hello \x1b[1;31mred\x1b[0m\r\nline2");

    const plain = try term.plainString(alloc);
    defer alloc.free(plain);
    try std.testing.expect(std.mem.indexOf(u8, plain, "hello red") != null);
    try std.testing.expect(std.mem.indexOf(u8, plain, "line2") != null);

    // Styled repaint contains the bold+red SGR introducer and content.
    var out: std.Io.Writer.Allocating = .init(alloc);
    defer out.deinit();
    var formatter: vt.formatter.TerminalFormatter = .init(&term, .{ .emit = .vt });
    formatter.extra = .{
        .palette = false,
        .modes = true,
        .scrolling_region = true,
        .tabstops = false,
        .pwd = false,
        .keyboard = true,
        .screen = .all,
    };
    try out.writer.print("{f}", .{formatter});
    const repainted = out.writer.buffered();
    try std.testing.expect(std.mem.indexOf(u8, repainted, "red") != null);
    try std.testing.expect(std.mem.indexOf(u8, repainted, "\x1b[") != null);
}
